### ISSUE TITLE
Installation Fix: Invalid Mount Configuration for "solr" Container

### ISSUE THREAD

**Issue by Qodestackr** [kartoza/SAEOSS-Portal#75]
Typed Command:
- `[qodestackr@qodestackr-pc docker]$ sudo ./compose.py --compose-file docker-compose.yml --compose-file docker-compose.dev.yml up`

Issue:
- `Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /solr/schema.xml
`

I understand that this suggests that Docker is attempting to bind-mount a file or directory from the host system to the container, but the source path specified does not exist on the host. However, the file paths do. 

The code section I believe is causing as issue is:
```YAML
  solr:
    ports:
      - target: 8983
        published: *solr-published-port
    volumes:
      - type: bind
        source: /home/qodestackr/Desktop/PROJECTS/KARTOZA/SAEOSS-Portal/docker/solr-schema.xml
        target: /opt/solr/server/solr/ckan/data
      # - solr-data:/opt/solr/server/solr/ckan/data
```

> Note that I tried to replace with absolute paths, it works for the rest( its just an installation workaround). Docker Engine restarts could not help much

Please guide me on how I can get started, any file permission( things like: `grep docker /etc/group` which already returns :point_right:  `docker:x:962:`)

Let me know anything I need to be aware of to get started.
